workflows:
  android-app:
    name: Android App
    max_build_duration: 600
    instance_type: mac_mini_m1
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Install Expo CLI
        script: npm install -g expo-cli eas-cli
      - name: Build Android APK
        script: |
          npx eas build --platform android --profile preview --non-interactive --no-wait
    artifacts:
      - build/**/outputs/apk/**/*.apk
